Attach tf version to the User-Agent header
gridscale/terraform-provider-gridscale pull request #111
Opened 2021-01-12 16:03 UTC by nvthongswansea

- Implement a part of #108.
- Attach tf version to the User-Agent header.

2021-01-12 16:31 UTC, bkircher requested changes

2021-01-12 16:31 UTC, bkircher commented on gridscale/provider.go
> +const version = "1.8.1"
Hmm, yeah. Might work for now. But we can get that thing from goreleaser I thing. Right?

```
builds:
    ldflags:
      - "-s -w -X github.com/gridscale/terraform-provider-gridscale/somePackage.GitCommit={{.Commit}} -X github.com/gridscale/terraform-provider-gridscale/somePackage.Version={{.Version}}"
```

This way it always works including "dirty" builds.

2021-01-14 09:01 UTC, nvthongswansea commented
@bkircher  test build command `go install -X main.version=testver -X main.commit=testcommit -X github.com/terraform-providers/terraform-provider-gridscale/gridscale.version=testver  -X github.com/terraform-providers/terraform-provider-gridscale/gridscale.commit=testcommit`. Run `terraform init`, and then run `TF_LOG=DEBUG terraform apply`.

2021-01-14 09:10 UTC, bkircher commented
I just tried this for testing but to no avail. Terraform implements some sort of TOFU model and remembers the hash of the TF provider binary in the dependency lock file

So this does not work:

- Build with `goreleaser build --snapshot --rm-dist`; this will create a binary in `dist/terraform-provider-gridscale_linux_amd64/`
- Go to a test TF project
- Do `terraform init`
- cp over our previously build binary
- run `terraform plan`
Any ideas?

2021-01-14 09:11 UTC, bkircher commented
Ah, just read your comment.

2021-01-14 09:24 UTC, nvthongswansea commented
> I just tried this for testing but to no avail. Terraform implements some sort of TOFU model and remembers the hash of the TF provider binary in the dependency lock file
> 
> So this does not work:
> 
> * Build with `goreleaser build --snapshot --rm-dist`; this will create a binary in `dist/terraform-provider-gridscale_linux_amd64/`
> * Go to a test TF project
> * Do `terraform init`
> * cp over our previously build binary
> * run `terraform plan`
>   Any ideas?

Just did what you told above. It works for me. The only extra steps are:
1. Change the name of `terraform-provider-gridscale_vv1.8.0-SNAPSHOT-...`binary file to `terraform-provider-gridscale`. Move this binary file to `.../go/bin/`.
2. Change the permission of the file, o.w permission denied error will happen (or it may just happen on my WSL).
3. Do your steps.

2021-01-14 09:25 UTC, nvthongswansea commented
@bkircher This is what I've got 
![image](https://user-images.githubusercontent.com/9968099/104571004-e25d3b80-5652-11eb-9853-b93a76f83452.png)

2021-01-14 09:51 UTC, bkircher commented
Got it. LGTM

2021-01-14 09:52 UTC, merged