Allow customizing request delay interval and maximum number of retries.
gridscale/terraform-provider-gridscale pull request #157
Opened 2021-04-27 17:41 UTC by nvthongswansea

Allow customizing request delay interval and maximum number of retries. Since there are some users applying moderate/large amount of concurrency on terraform, customizing these parameters would solve some issues relating to the rate limit. Changes:
- Read custom request delay interval from the arg `request_delay_int`. If `request_delay_int` is omitted, read from the env var `GRIDSCALE_TF_REQUEST_DELAY_INT`.
- Read maximum number of retries from the arg `max_n_retries`. If `max_n_retries` is omitted, read from the env var `GRIDSCALE_TF_MAX_N_RETRIES`.
- Update the docs.

2021-04-28 09:30 UTC, bkircher requested changes
Okay in general. I would suggest a name change, though, for that delay interval setting.

The main thing: Do we really need `max_n_retries` to be 5? Why is not 1 the default?

I would expect the provider to fail more often, but these are then 
1. Probably real bugs that will fail again in the next retry anyway
2. Are not bugs in the backend but other failures that should not be retried anyway (examples is permission denied)

`max_n_retries` of 1 would, I suppose, decrease load on the system overall.

What is your opinion?

2021-04-28 09:30 UTC, bkircher commented on website/docs/index.html.markdown
> +* `request_delay_int` - (Optional) Custom request delay interval in Ms. This time interval is used to delay the synchronous request checks, or delay retryable requests. If omitted, the GRIDSCALE_TF_R
Change `Ms` to `ms`.

2021-04-28 09:30 UTC, bkircher commented on gridscale/provider.go
> +				Description: "Custom request delay interval in Ms. This time interval is used to delay the synchronous request checks, or delay retryable requests.",
Change `request_delay_int` to `request_delay_interval` and `GRIDSCALE_TF_REQUEST_DELAY_INT` to `GRIDSCALE_TF_REQUEST_DELAY_INTERVAL`, respectively.

2021-04-28 09:47 UTC, nvthongswansea commented
@bkircher Answers:
1. The default value 5 of `max_n_retries` is from `gsclient-go` (we've used this default value since the beginning). This `max_n_retries` should be used in case user want to deal with the rate limiter when using moderate amount of concurrency. Usually, these 2 variables are not used in normal case where everything runs ok.
2. Which requests are retriable, which are not. These 2 questions belong to `gsclient-go`.

2021-04-29 08:28 UTC, bkircher commented
>   The default value 5 of max_n_retries is from gsclient-go (we've used this default value since the beginning). This max_n_retries should be used in case user want to deal with the rate limiter when using moderate amount of concurrency. Usually, these 2 variables are not used in normal case in which everything runs ok.

I know what it does. I just think the value should be 1 instead of 5. (Example: In gscloud, the value is set to 1.)


>    Which requests are retriable, which are not? These 2 questions' answers belong to gsclient-go.

Not all HTTP methods make sense to retry. Also, retrying 429 is different from say 503. One might include a `Retry-After:` header the other might not.

Other responses, say 500 or 404, or 400 do not make sense to retry at all. Is gsclient-go taking care of this?

2021-04-29 08:31 UTC, nvthongswansea commented
@bkircher Again, the retriable request concern belongs to `gsclient-go`, precisely, [here](https://github.com/gridscale/gsclient-go/blob/master/request.go#L279).

2021-04-29 09:05 UTC, bkircher commented
> Again, the retriable request concern belongs to gsclient-go, precisely, here.

Thanks for the link. I think this is a completely wrong handling of retries.

429 should re-tried indefinitely (or stopped on signals like SIGINT)

503 should also be retried but blocking on `Retry-After`value. There a `max_n_retries` value might make sense.

As for 
- 409
- 424 and
- 500

Those should not be retried at all. IMO.

2021-04-29 09:10 UTC, nvthongswansea commented
> > Again, the retriable request concern belongs to gsclient-go, precisely, here.
> 
> Thanks for the link. I think this is a completely wrong handling of retries.
> 
> 429 should re-tried indefinitely (or stopped on signals like SIGINT)
> 
> 503 should also be retried but blocking on `Retry-After`value. There a `max_n_retries` value might make sense.
> 
> As for
> 
> * 409
> * 424 and
> * 500
> 
> Those should not be retried at all. IMO.

Could you open an issue in `gsclient-go` repo, please? I will set the default n retries to 1 in this PR for our tf provider.

2021-04-29 09:14 UTC, bkircher commented
> Could you open an issue in gsclient-go repo, please? 

Okay, will do.

> I will set the default n retries to 1 in this PR for our tf provider.

If I understand the code in gsclient-go correctly now, we want something like > 1 (e.g. the 5 you suggested). But that doesn't make it correct. It just might work in more cases by default than giving 1 here.

2021-04-29 09:21 UTC, bkircher commented
So IMO, we can merge this here. It is just not the correct solution (or full solution) to the problem at hand. @nvthongswansea  Okay with merging here?

2021-04-29 09:22 UTC, nvthongswansea commented
> If I understand the code in gsclient-go correctly now, we want something like > 1 (e.g. the 5 you suggested). But that doesn't make it correct. It just might work in more cases by default than giving 1 here.

The default `max_n_retries` in `gsclient-go` doesn't relate to the `max_n_retries` in terraform provider, since we use `gsclient.NewConfiguration()` instead of `gsclient.DefaultConfiguration()` to initialize a client in terraform. So that in terraform provider, we have to manually set the default value of `max_n_retries` ([here](https://github.com/gridscale/terraform-provider-gridscale/blob/master/gridscale/config.go#L26)).

2021-04-29 09:23 UTC, nvthongswansea commented
> So IMO, we can merge this here. It is just not the correct solution (or full solution) to the problem at hand. @nvthongswansea Okay with merging here?

Yep. But let me change the default value of `max_n_retries` in our tf provider firstly.

2021-04-29 09:41 UTC, nvthongswansea commented
@bkircher done.

2021-05-09 08:38 UTC, merged